@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
    "test" : "post test",
    "make": "Test Make",
    "model": "Test Model",
    "year": 2626
}

###
@newCar = {{postACar.response.body._id}}

###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json

###

DELETE  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/6ab16c7815b79c091f7edbf9 HTTP/3.0
content-type: application/json

{
    "test" : "put test",
    "make": "Test Make",
    "model": "Test Model",
    "year": 2023
}

###
GET {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah